WebApplication/WebApplication2/Controllers/ImageWebController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ImageWebController : Controller
    {
        static ImageWeb ImageViewInfo = new ImageWeb();
        public ImageWebController()
        {
        }

        // GET: ImageWeb
        public ActionResult WebImageFront()
        {
            ImageViewInfo.CheckConnection();
            ViewBag.Status= ImageViewInfo.Status;
            ViewBag.Count = ImageViewInfo.NumberOfImages();
            return View(ImageViewInfo);
        }
    }
}

WebApplication/WebApplication2/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class PhotoController : Controller
    {
        private PhotoAlbum photos = new PhotoAlbum();
        private static string currentImagePath;
        private static string currentThumbPath;

        // GET: Photo
        public ActionResult PhotoView()
        {
            return View(photos.PhotosAlbum);
        }
        public ActionResult DeletePhoto(string name, string thumbPath, string photoPath, string photoRelThumb)
        {
            currentImagePath = photoPath;
            currentThumbPath = thumbPath;
            ViewBag.path = photoRelThumb;
            ViewBag.name = name;
            return View();
        }
        public ActionResult RemovePhoto()
        {
            System.IO.File.Delete(currentThumbPath);
            System.IO.File.Delete(currentImagePath);
            Thread.Sleep(2000);
            return RedirectToAction("PhotoView");
        }
        public ActionResult ViewerPhoto(string photoRelPath, string name, string year, string month, string thumbPath, string photoPath)
        {
            currentImagePath = photoPath;
            currentThumbPath = thumbPath;
            ViewBag.path = photoRelPath;
            ViewBag.name = name;
            ViewBag.year = year;
            ViewBag.month = month;
            return View();
        }
    }
}

WebApplication/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ImageService</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ImageService - Web Application", "WebImageFront", "ImageWeb", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Configuration", "ConfigurationView", "Configuration")</li>
                    <li>@Html.ActionLink("Logs", "LogsView", "Logs")</li>
                    <li>@Html.ActionLink("Photos", "PhotoView", "Photo")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hazan & Cohen Ltd.</p>
        </footer>
    </div>

</body>
</html>